# Generated by Django 3.0.5 on 2020-04-14 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(max_length=50)),
                ('feed_description', models.TextField(default='')),
                ('feed_composition', models.TextField(default='')),
                ('feed_nutrition', models.TextField(default='')),
                ('feed_cost', models.FloatField()),
                ('feed_img', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='table_pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.feed')),
            ],
        ),
    ]
