# Generated by Django 3.0.5 on 2020-04-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='feed',
        ),
        migrations.DeleteModel(
            name='table_pass',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='feed',
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
