# Generated by Django 3.0.5 on 2020-04-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shavershan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='feed_composition',
            new_name='composition',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='feed_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='feed_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='feed_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='feed_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='feed_nutrition',
            new_name='nutrition',
        ),
    ]
