# Generated by Django 3.0.5 on 2020-04-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shavershan', '0003_auto_20200415_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
