# Generated by Django 3.0.5 on 2020-04-16 16:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shavershan', '0004_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='confirmed_order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shavershan.order')),
            ],
        ),
    ]
