# Generated by Django 3.0.5 on 2020-04-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shavershan', '0006_confirmed_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmed_order',
            name='customer',
        ),
    ]
