# Generated by Django 3.0.5 on 2020-04-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shavershan', '0007_remove_confirmed_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
