# Generated by Django 3.0.5 on 2020-04-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shavershan', '0009_auto_20200416_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmed_order',
            name='order',
        ),
        migrations.AddField(
            model_name='confirmed_order',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shavershan.order'),
        ),
    ]
