# Generated by Django 3.0.5 on 2020-04-16 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shavershan', '0010_auto_20200416_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmed_order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shavershan.order'),
        ),
    ]
