# Generated by Django 3.0.5 on 2020-04-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shavershan', '0011_auto_20200416_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='confirmed_order',
        ),
    ]
